### ISSUE TITLE
Code organization cleanup

### ISSUE THREAD

**Issue by psionic-k** [cargo2nix/cargo2nix#228]
# Psuedo Code

This section describes what happens and then maps the concept to actual code entry point

### Generating the Cargo.nix

**main.rs**
- Use cargo lib to get toml & lock information (doesn't get .cargo/config.toml info yet #181 )
- Walk down the dependency DAG marking any explicit dependencies required and recording where any top-level workspace crate or feature activates features / dependencies farther down the DAG
- make a `BuildPlan` and generate some expressions that are rendered in the `Cargo.nix.tera` template

### Consuming the Cargo.nix

- nixpkgs instantiated with the combined cargo2nix overlay (see older version 0.10.0 for separate overlay style)
- this adds `rustBuilder`
- pass your Cargo.nix into `makePackageSet'` as the `packageFun`.  It will be called later with some of the arguments you pass into `makePackageSet`

**makePackagSet'`

- In `simplified.nix` build (or accept) a `rustToolchain` using rust-overlay
- Pass this into the `full.nix` (note the call inside the call with buildPackages for the buildPlatform)
- Inside full.nix, the overrides get applied to each rust crate as necessary
- The nix magic splice happens via `lib/splice.nix` so that our lazily recursive DAG can be assembled
- The final derivations for each dependency result from calls to `mkCrate.nix`
- A lot of the bash for `mkCrate.nix` is found in `overlay/utils.sh`

- A package set can be used to
  - create a shell
  - expose a bin crate in a flake output  (Note, these are functions like `rustPkgs.workspace.cargo2nix {}` and can be called to obtain a derivation with a different profile etc, see arguments in mkCrate.nix)
  - make an output that runs unit tests in the sandbox

### Building Each Derivation

- The derivations are fairly usual, `unpackPhase`  `configurePhase` `buildPhase` `installPhase`
- The source Cargo.toml etc are moved out of the way and replaced with synthetic ones because we intend to control almost every aspect of linkage and features through flags or synthetic configs
- Before the actual build command, cargo is configured by reading inputs from dependencies (that were recorded and passed up through the DAG, see utils.sh for these pre and post functions)
- After the build, a new set of rlib link flags and other info is generated from cargo metadata and dependency info to continue passing up the DAG so that successive crates can find all of their information
- bin crates copy a smaller set of outputs to a bin attribute avoid polluting nix profiles

# TODO Fix up

This section catalogues where the entry points and flow control in the above aren't well semantically arranged.

- [ ] simplified.nix calls full.nix.  makePackageSet' is within simplified.nix.  Simplified is not a simpler version of full.nix.  It's some kind of shim or trampoline structure.  full.nix "ties the knot" or whatever we say in Nix lang.
- [ ] utils.sh is all related to making crates
- [ ] rust-triple.nix needs to be deprecated for the nixpkgs function, possibly offloading to rust-overlay if that package chooses to override this function (which is said to fall behind sometimes)

# TODO Not documented

Describe role and point in flow control for each

- [ ] profiles.nix
- [ ] fetch.nix

**Respond to this issue with any architecture questions and I will attempt to clarify how things work and possibly decide to make some changes**

**Comment by psionic-k** [comment]
PR to fix [nixpkgs](https://github.com/NixOS/nixpkgs/pull/146274) treatment of wasi platform is one to watch. 

See unstable version here:
https://github.com/NixOS/nixpkgs/blob/nixpkgs-unstable/pkgs/build-support/rust/lib/default.nix

Issue that brought the Rust triple treatment to light
https://github.com/oxalica/rust-overlay/issues/57

**Comment by psionic-k** [comment]
mkRustCrate arguments need to be gathered into one attrSet.  The bloated signatures are annoying and require updating for the same structure over and over.
